import {
  type ModuleExecutionContext,
  type SessionBrief,
  sessionBriefSchema,
  type SessionDraft,
  sessionDraftSchema,
  type SlideOutline,
  slideOutlineSchema
} from "@tsa/schemas";

export interface SchedulingProvider {
  createSessionDraft(input: { brief: SessionBrief; slideOutline: SlideOutline }, context: ModuleExecutionContext): Promise<SessionDraft>;
}

export class MockSchedulingProvider implements SchedulingProvider {
  async createSessionDraft(input: { brief: SessionBrief; slideOutline: SlideOutline }, _context: ModuleExecutionContext): Promise<SessionDraft> {
    const brief = sessionBriefSchema.parse(input.brief);
    const slideOutline = slideOutlineSchema.parse(input.slideOutline);
    const scheduledFor = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();

    return sessionDraftSchema.parse({
      sessionId: `session-${brief.topicId}`,
      topicId: brief.topicId,
      title: brief.title,
      scheduledFor,
      durationMinutes: 60,
      location: "TBD meeting room or video call",
      brief,
      slideOutline,
      notifications: [
        {
          channel: "slack",
          subject: `Vote result: ${brief.title}`,
          body: `Mock notification: next sharing topic is "${brief.title}". Please review the brief before the session.`,
          recipients: ["#team-sharing"]
        },
        {
          channel: "calendar",
          subject: `Team Sharing: ${brief.title}`,
          body: "Mock calendar draft generated by Scheduling Module.",
          recipients: brief.audience
        }
      ]
    });
  }
}

export class RealSchedulingProvider implements SchedulingProvider {
  async createSessionDraft(_input: { brief: SessionBrief; slideOutline: SlideOutline }, _context: ModuleExecutionContext): Promise<SessionDraft> {
    throw new Error("RealSchedulingProvider is not implemented. Replace it with Calendar, Slack, email, or booking integrations.");
  }
}
